Charles/transactionsh header
calblueprint/sunday-friends-mobile pull request #6
Opened 2022-02-25 17:15 UTC by CharlesMing02

## Documentation

- created transactions group component and subcomponents in the header
- includes button group, searchbar (imported from react-native-paper with some custom styling), and filters button
- button group and searchbar respond to touches/have state to be used later

## Related PRs

_Describe any other PRs that might affect/depend on yours_
Will probably change some styling once we have the global stylesheet

## Testing

_List all manual tests done/new unit tests you have implemented_

_Optional - any related PRs you're waiting on, or PRs that will conflict, etc_

## Screenshots

_Required for visual changes_

CC: @jacobjk01 @hukellyy

2022-03-01 19:30 UTC, jacobjk01 commented on src/components/TransactionsGroup.tsx
> +                        <Text style={styles.filtersButtonText}>Filters (0)</Text>
Just reminder that we want to use pressables instead of touchable opacities (you know that already)
Switch this over when u get the chance

2022-03-04 09:04 UTC, CharlesMing02 commented
sorry I forgot to make a new branch for the transactions list, will do so for future changes

2022-03-06 23:13 UTC, CharlesMing02 commented
Notes for review:

**Documentation**
- changed buttons to pressables
- created and styled transactions list
- created and styled components for the list (called transaction preview)
- files outside of those components: imported two smiley pngs, imported DM Mono font

**Related PRs**
Describe any other PRs that might affect/depend on yours
Will probably change some styling once we have the global stylesheet

Optional - any related PRs you're waiting on, or PRs that will conflict, etc
- Todo: a lot of styling isn't exactly the same as figma. I will message Kelly to discuss. It might be helpful for me to wait for the hifi figma to be done before changing all the styling and move on to the modal for now.
- 
**Screenshots**
![1EC92597-302B-4B1B-BCC8-420CC2D21B33](https://user-images.githubusercontent.com/70979542/156946308-a573e69d-8205-44dc-a4c7-77871e4c5c35.png)

2022-03-08 01:43 UTC, jacobjk01 commented on src/components/TransactionsGroup/TransactionPreview/TransactionPreview.tsx
> +                    <FontAwesome5 name="chevron-right" size={24} color="#CACACA"/>
Switch to svg icon! resolve this if you're doing it in your next branch.

2022-03-08 02:47 UTC, hukellyy commented
good job charlie!!! overall rlly solid just a few nits: 
1. search by text is pretty large relative to the other text sizes ;; would make it a similar size to 'filters'
2. for final styling i think i may increase the font size of the bolded text in each row (ie the "volunteered at...") 
3. padding a bit thicc on the filters button but i will comment more specifically ab that in another comment

2022-03-08 02:54 UTC, hukellyy requested changes

2022-03-08 02:54 UTC, hukellyy commented on src/components/TransactionsGroup/styles.tsx
> +        fontWeight: "800"
can u make the top and bottom padding for filters button 8px on each size ! or whatevr the equivalent of that is if ur not using pixels -- tldr just make padding smaller

2022-03-08 02:54 UTC, hukellyy commented on src/components/TransactionsGroup/styles.tsx
> +        fontWeight: "800"
similarly make sure the search bar matches that size ,, i'm not sure if u modelled the search bar from web but it should be slightly smaller once i make the mobile component for that

2022-03-11 04:14 UTC, merged